### ISSUE TITLE
Publish to artifactory

### ISSUE THREAD

**Issue by vladimirshefer** [hrakaroo/glob-library-java#1]
This library is perfect, but how do I use it in my project?

Please, publish the jar to mvn or jcenter.

**Comment by hrakaroo** [comment]
Hello!  I'm glad you find it useful.  It should be published on 

https://search.maven.org/search?q=g:com.hrakaroo

Let me know if you have any issues using it.

Cheers,
   Joshua

**Comment by vladimirshefer** [comment]
Why isn't it mentioned in README?

**Comment by vladimirshefer** [comment]
https://github.com/hrakaroo/glob-library-java/pull/2
